<#
.SYNOPSIS
    release.ps1 -- repeatable release/export command for the skill-mesh public
    package (Step 38). Stages ONLY the source repository's git-tracked files,
    builds both host distributions into the stage, runs the package-integrity
    gate against the staged artifacts (with the no-tracked-dist check enforced
    against the SOURCE repository's own index), and emits a deterministic
    CHECKSUMS manifest over the generated distribution artifacts.

.DESCRIPTION
    Four phases, each gating the next -- a release that fails a phase is never
    left looking green:

      1. STAGE    Enumerate SourceRoot's TRACKED files via `git ls-files` and
                  copy exactly those paths into a clean StageDir. A release
                  must contain only committed content: this is authoritative
                  (git's own index), never a hand-maintained denylist, so it
                  can never leak an untracked scratch file, local note, or
                  another worktree's stray file into the released artifact --
                  and it naturally excludes '.git' (git never tracks itself)
                  without needing to special-case its worktree-file-vs-
                  directory shape.
      2. BUILD    Invoke the STAGED tools\build-distributions.ps1 (NOT the
                  source copy), so the release exercises exactly the tool a
                  consumer of this repository would run, producing
                  StageDir\dist\claude and StageDir\dist\gpt.
      3. CHECK    Run `python -m pytest tests\package-integrity` FROM WITHIN
                  StageDir, so every test's repo-root resolution
                  (Path(__file__).resolve().parents[2]) naturally points at the
                  STAGED tree, not the source tree -- the release is graded by
                  the exact same checker code as a normal `pytest tests/` run,
                  never a re-implemented parallel checker. SKILL_MESH_SOURCE_ROOT
                  is set to SourceRoot for this invocation so the
                  no-tracked-dist check runs against the SOURCE repository's own
                  `git ls-files` (which still has '.git') instead of silently
                  skipping against the (deliberately git-less) stage -- a
                  `git add -f`'d dist/ path is caught even though
                  build-distributions.ps1 would otherwise wipe/regenerate
                  dist/claude and dist/gpt and erase the evidence from the
                  stage itself before checksums are computed. A failing check
                  ABORTS the release (non-zero exit, no CHECKSUMS written); the
                  staged output is left in place for inspection.
      4. CHECKSUM Hash every file under StageDir\dist (SHA-256; the
                  deterministically-GENERATED artifacts a consumer actually
                  installs and would want to verify -- build-distributions.ps1
                  already normalizes line endings/BOM when producing them, so
                  they reproduce byte-for-byte independent of the source
                  checkout's incidental line-ending/autocrlf history, which raw
                  source-tree bytes do NOT) and write CHECKSUMS.txt, sorted by
                  path, with no wall-clock timestamp.

    DETERMINISM: file modification times are never hashed and no artifact body
    embeds a date/time; two runs over an unchanged source tree reproduce the
    identical dist/ file set and identical file contents (byte-for-byte), so
    CHECKSUMS.txt is identical across runs -- and stays identical even if the
    SOURCE checkout's line endings differ (CRLF vs LF, a fresh clone vs this
    machine's autocrlf history), because only the normalized GENERATED bytes
    are hashed.

    DESTRUCTIVE-DELETE SAFETY: StageDir is canonicalized via
    runtime/path-guard.ps1's Get-CanonicalRealPath (resolves '..'/reparse
    points/trailing-separator variants to one real path, so a trailing
    backslash or a junction cannot smuggle a different target past a naive
    string compare) and is refused outright if it equals SourceRoot's real
    path OR is an ANCESTOR of it (deleting StageDir would then delete the
    source). A pre-existing, non-empty StageDir is refused unless it carries
    this script's own marker file from a prior run (proof this script created
    it) -- an arbitrary caller-supplied directory full of unrelated content is
    never silently wiped.

.PARAMETER StageDir
    Clean staging root. Default: <repo>\release-stage (gitignored).

.PARAMETER SourceRoot
    Git checkout to stage (must be a git working tree; `git ls-files` is the
    staging source of truth). Default: this script's own repository (the
    normal case). Test seam: tests/release/test_release_script.py points this
    at an isolated throwaway git repo to prove the CHECK phase actually aborts
    the release on a planted defect, without ever touching this repository's
    own git state.

.PARAMETER Provider
    Passed through to build-distributions.ps1 verbatim: a single 'claude' | 'gpt' |
    'codex', or a set -- 'both' (default) = claude + gpt, 'all' = claude + gpt + codex.
    See the param block for why the default is still 'both'.

.PARAMETER PythonExe
    Interpreter used for the package-integrity gate (phase 3). Default:
    'python'.

.EXAMPLE
    powershell -File tools\release.ps1
    powershell -File tools\release.ps1 -StageDir C:\stage\release -Provider claude
#>

[CmdletBinding()]
param(
    [string]$StageDir = '',

    [string]$SourceRoot = '',

    # Mirrors build-distributions.ps1's set exactly -- this value is forwarded to it
    # verbatim (Phase 2 below), so a value legal here and illegal there would fail
    # mid-release with the builder's error rather than at parameter binding.
    #
    # The default stays 'both' (claude + gpt) ON PURPOSE now that a third provider
    # exists. Phase CP Step 5 gave codex a discovery root and an install path, so the
    # original reason ("no install path can consume it") is spent -- but the default
    # does NOT widen, for a second reason that is not: the codex adapter roster is a
    # rollout in progress (5 of 47 portable skills at Step 5), so 'all' would ship a
    # deliberately partial profile as if it were the catalog. Ship codex in a release
    # by asking for it -- '-Provider all', or '-Provider codex' for a codex-only
    # artifact. Revisit the default when the codex roster reaches the portable roster.
    # Note that tools/migrate-legacy-install.ps1 binds exactly the profiles the dist
    # ships, so a 'both' release stays a complete, migratable artifact.
    [ValidateSet('claude', 'gpt', 'codex', 'both', 'all')]
    [string]$Provider = 'both',

    [string]$PythonExe = 'python'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# -- Path resolution ------------------------------------------------------------

$TOOLS_DIR = $PSScriptRoot
$REPO_ROOT = Split-Path -Parent $TOOLS_DIR
$PATH_GUARD = Join-Path $REPO_ROOT 'runtime\path-guard.ps1'

# Reuse the Step-34 path guard's canonicalization (resolves '..', trailing
# separators, and junctions/symlinks to one real path) -- single source of
# truth for "what does this path REALLY resolve to", shared with
# build-distributions.ps1 and install-skill-mesh.ps1.
. $PATH_GUARD

if ([string]::IsNullOrWhiteSpace($SourceRoot)) {
    $SourceRoot = $REPO_ROOT
}
if ([string]::IsNullOrWhiteSpace($StageDir)) {
    $StageDir = Join-Path $REPO_ROOT 'release-stage'
}

# Get-CanonicalRealPath appends a non-existing tail verbatim to the resolved
# existing prefix, so this works whether or not StageDir already exists.
$sourceRootFull = Get-CanonicalRealPath -InputPath $SourceRoot
$StageDir = Get-CanonicalRealPath -InputPath $StageDir

if ($StageDir.Equals($sourceRootFull, [System.StringComparison]::OrdinalIgnoreCase)) {
    throw "release: -StageDir must not be the same as the source root ($sourceRootFull)"
}
if (Test-PathUnderRoot -Candidate $sourceRootFull -Root $StageDir) {
    throw ("release: -StageDir '$StageDir' is an ANCESTOR of the source root " +
           "'$sourceRootFull' -- refusing (clearing the stage would delete the source). " +
           "Point -StageDir at a directory that does not contain the source checkout.")
}
# The reverse (StageDir living INSIDE the source root, e.g. the documented
# default <repo>\release-stage) is expected and safe: only the StageDir
# subtree is ever removed, never an ancestor of it.

$STAGE_MARKER = '.skill-mesh-release-stage-marker'
if (Test-Path -LiteralPath $StageDir) {
    $existing = @(Get-ChildItem -LiteralPath $StageDir -Force)
    $hasMarker = Test-Path -LiteralPath (Join-Path $StageDir $STAGE_MARKER)
    if ($existing.Count -gt 0 -and -not $hasMarker) {
        throw ("release: -StageDir '$StageDir' already exists, is non-empty, and carries no " +
               "marker proving a prior release.ps1 run created it; refusing to delete it. " +
               "Point -StageDir at an empty directory, or one this script previously staged.")
    }
    Remove-Item -LiteralPath $StageDir -Recurse -Force
}
New-Item -ItemType Directory -Path $StageDir -Force | Out-Null
New-Item -ItemType File -Path (Join-Path $StageDir $STAGE_MARKER) -Force | Out-Null

Write-Host "release: staging tracked files from $sourceRootFull -> $StageDir"

# -- Phase 1: STAGE (git-tracked files only; a release is only committed content) --

$isWorkTree = & git -C $sourceRootFull rev-parse --is-inside-work-tree 2>$null
if ($LASTEXITCODE -ne 0 -or $isWorkTree -ne 'true') {
    throw "release: -SourceRoot '$sourceRootFull' is not a git working tree (git ls-files staging requires one)"
}
$trackedOutput = & git -C $sourceRootFull ls-files
if ($LASTEXITCODE -ne 0) {
    throw "release: 'git -C $sourceRootFull ls-files' failed (exit $LASTEXITCODE)"
}
# Native stdout capture already splits on newlines into an array; @() guards
# the single-line-output edge case (PowerShell would otherwise return a bare
# string, which the foreach below would then iterate CHARACTER by character).
$trackedPaths = @($trackedOutput) | Where-Object { $_ -and $_.Trim() -ne '' }
if ($trackedPaths.Count -eq 0) {
    throw "release: 'git ls-files' returned no tracked paths under $sourceRootFull -- nothing to release"
}

$copied = 0
foreach ($rel in $trackedPaths) {
    $relWin = $rel -replace '/', '\'
    $srcFile = Join-Path $sourceRootFull $relWin
    if (-not (Test-Path -LiteralPath $srcFile -PathType Leaf)) {
        # Tracked in the index but absent from the working tree (rare
        # index/worktree mismatch, e.g. a deleted-but-not-yet-`git rm`d file);
        # skip rather than error -- there is nothing to copy.
        continue
    }
    $destFile = Join-Path $StageDir $relWin
    $destDir = Split-Path -Parent $destFile
    if (-not (Test-Path -LiteralPath $destDir)) {
        New-Item -ItemType Directory -Path $destDir -Force | Out-Null
    }
    Copy-Item -LiteralPath $srcFile -Destination $destFile -Force
    $copied++
}
Write-Host "release: staged $copied tracked file(s)"

# -- Phase 2: BUILD (invoke the STAGED builder, not the source copy) --------

$stagedBuildScript = Join-Path $StageDir 'tools\build-distributions.ps1'
if (-not (Test-Path -LiteralPath $stagedBuildScript)) {
    throw "release: staged build-distributions.ps1 missing at $stagedBuildScript (is it git-tracked in $sourceRootFull ?)"
}
$distDir = Join-Path $StageDir 'dist'

# Spawn in a SEPARATE process: the builder's terminal 'exit 0' would otherwise
# terminate this parent script (same-process 'exit' semantics), mirroring the
# pattern already used by tools/install-skill-mesh.ps1.
$psExe = (Get-Process -Id $PID).Path
if ([string]::IsNullOrWhiteSpace($psExe)) { $psExe = 'powershell' }
& $psExe -NoProfile -NonInteractive -File $stagedBuildScript -OutputDir $distDir -Provider $Provider
if ($LASTEXITCODE -ne 0) {
    throw "release: build-distributions.ps1 failed (exit $LASTEXITCODE); staged output left at $StageDir"
}

# -- Phase 3: CHECK (package-integrity gate against the STAGED artifacts) ---

Write-Host "release: running package-integrity checks against the staged tree"
Push-Location $StageDir
# Point the no-tracked-dist check at the SOURCE repository's own git index
# (still has '.git', unlike the stage) so it genuinely RUNS -- not skips --
# during a real release, and catches a `git add -f`'d dist/ path even though
# build-distributions.ps1 will have already wiped/regenerated dist/claude and
# dist/gpt by the time this runs.
$env:SKILL_MESH_SOURCE_ROOT = $sourceRootFull
try {
    # -p no:cacheprovider: running pytest FROM WITHIN the stage would otherwise
    # write its own .pytest_cache into the tree. Belt-and-suspenders cleanup
    # below removes any cache dir regardless (also covers stray __pycache__
    # from importing test modules) so the stage stays tidy for inspection.
    & $PythonExe -m pytest 'tests/package-integrity' -q -p no:cacheprovider
    $checkExit = $LASTEXITCODE
} finally {
    Remove-Item Env:\SKILL_MESH_SOURCE_ROOT -ErrorAction SilentlyContinue
    Pop-Location
}
if ($checkExit -ne 0) {
    throw ("release: package-integrity checks FAILED against the staged release " +
           "(exit $checkExit); staged output left at $StageDir for inspection. " +
           "No CHECKSUMS were written.")
}

# Remove any cache directory the CHECK phase itself created inside the stage.
Get-ChildItem -LiteralPath $StageDir -Recurse -Directory -Force |
    Where-Object { $_.Name -eq '.pytest_cache' -or $_.Name -eq '__pycache__' } |
    Sort-Object -Property FullName -Descending |
    ForEach-Object {
        if (Test-Path -LiteralPath $_.FullName) {
            Remove-Item -LiteralPath $_.FullName -Recurse -Force
        }
    }

# -- Phase 4: CHECKSUM (dist/ only -- deterministic; no wall-clock in body) --

$checksumPath = Join-Path $StageDir 'CHECKSUMS.txt'
$files = Get-ChildItem -LiteralPath $distDir -Recurse -File | Sort-Object -Property FullName

$lines = New-Object System.Collections.Generic.List[string]
foreach ($f in $files) {
    $hash = (Get-FileHash -LiteralPath $f.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
    $rel = ($f.FullName.Substring($StageDir.Length).TrimStart('\', '/')) -replace '\\', '/'
    $lines.Add("$hash  $rel")
}

$header = @(
    '# skill-mesh release checksums (SHA-256 over dist/ -- the generated,',
    '# host-installable artifacts; the deterministic output of',
    '# build-distributions.ps1, not the raw source checkout).',
    '# Generated by tools/release.ps1 -- no wall-clock timestamp is embedded, so',
    '# an unchanged working tree reproduces this file byte-for-byte.'
)
$body = (($header + [string[]]$lines) -join "`n") + "`n"
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($checksumPath, $body, $utf8NoBom)

Write-Host "release: checksummed $($files.Count) dist/ file(s); CHECKSUMS.txt written to $checksumPath"
Write-Host "release: done. StageDir = $StageDir"
exit 0
